networks:
  default:
    driver: bridge
    name: doctor
    # external: true
volumes:
  doctor:

services:
  mysql:
    image: vidya07422/doctor-mysql:v1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: DoctorApp1
    volumes:
      - doctor:/var/lib/mysql
  backend:
    image: vidya07422/doctor-backend:v1
    container_name: backend
    environment:
      DB_HOST: mysql 
      DB_USERNAME: doctor 
      DB_PASSWORD: DoctorApp1  
    depends_on:
    - mysql
  frontend:
    image: vidya07422/doctor-frontend:v1
    container_name: frontend
    ports: 
    - "80:80"
    depends_on:
    - backend

